schedule:
  jobConfigs:
    mail:
      Config:
      cron: '*/10 * * * * *'
      autostart: true
      targetType: MessageQueueIngester
      targetInputs:
        topic: eap_mail
      query: SELECT * FROM public.eap_mail_sender WHERE isexecuted = false AND processid = 0;
      updateQuery: UPDATE public.eap_mail_sender SET processid = ?, initiateddate = ? WHERE id = ?;
      updateInputs:
        processid: INTEGER
        initiateddate: TIMESTAMP
        id: INTEGER

    sms:
      Config:
      cron: '*/15 * * * * *'
      autostart: true
      targetType: MessageQueueIngester
      targetInputs:
        topic: eap_sms
      query: SELECT * FROM public.eap_sms_sender WHERE isexecuted = false AND processid = 0;
      updateQuery: UPDATE public.eap_sms_sender SET processid = ?, initiateddate = ? WHERE id = ?;
      updateInputs:
        processid: INTEGER
        initiateddate: TIMESTAMP
        id: INTEGER