schedule:
  jobConfigs:
    mail:
      Config:
      method: mail
      cron: '*/10 * * * * *'
      autostart: true
      targetType: MQ
      targetInputs:
        topic: eap_mail
      query: SELECT * FROM public.eap_mail_sender WHERE isexecuted = ? AND processid = ?;
      inputs:
        isexecuted: BOOLEAN
        processid: INTEGER
      updateQuery: UPDATE public.eap_mail_sender SET processid = ?, initiateddate = ? WHERE id = ?;
      updateInputs:
        processid: INTEGER
        initiateddate: TIMESTAMP
        id: INTEGER

    sms:
      Config:
      method: sms
      cron: '*/15 * * * * *'
      autostart: false
      targetType: MessageQueue
      targetInputs:
        topic: eap_sms
      query: SELECT * FROM public.eap_sms_sender WHERE isexecuted = ? AND processid = ?;
      inputs:
        isexecuted: BOOLEAN
        processid: INTEGER
      updateQuery: UPDATE public.eap_sms_sender SET processid = ?, initiateddate = ? WHERE id = ?;
      updateInputs:
        processid: INTEGER
        initiateddate: TIMESTAMP
        id: INTEGER